import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import { SCREENS } from '../variables/Variables'
import {PostCard,PostWidget,Categories, SearchBar} from "../components/";
import {getPosts} from '../services'
import { FeaturedPosts } from '../sections/index';
import { useMediaQuery } from 'react-responsive'
import { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faAnglesDown } from '@fortawesome/free-solid-svg-icons'

const Container = styled.div`
  margin:0 auto;
  margin-bottom: 2rem ;
  padding:0 3rem;
  width:100% ;

  @media screen and (max-width: ${SCREENS.sm}){
    max-width: ${SCREENS.sm} ;
  }
  @media screen and (max-width: ${SCREENS.md}){
    max-width: ${SCREENS.md} ;
    padding:0 1rem;
  }
  @media screen and (max-width: ${SCREENS.lg}){
    max-width: ${SCREENS.lg} ;
 
  }
  @media screen and (max-width: ${SCREENS.xl}){
    max-width: ${SCREENS.xl} ;
    padding:0 2rem;
  }
  @media screen and (max-width: ${SCREENS['2xl']}){
    max-width: ${SCREENS['2xl']} ;
  }
`
const BodyContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(12, minmax(0, 1fr));
  gap:3rem;
  @media screen and (max-width: ${SCREENS.lg}){
    grid-template-columns: repeat(1, minmax(0, 1fr));
  }
`
const PostsContainer = styled.div`
    grid-column: 1/ 9;
    display:grid ;
    grid-template-columns:repeat(2,1fr) ;
    gap:1rem;
    @media screen and (max-width: ${SCREENS.lg}){
    grid-column: 1 ;
    grid-template-columns:repeat(1,1fr) ;
  }
`
const SideContainer = styled.div`
    grid-column: 9/ 13;
    @media screen and (max-width: ${SCREENS.lg}){
    grid-column: 1 ;
    }
`
const SideBarContainer=styled.div`
    position: sticky ;
    top:2rem;
`
const SearchBarMobile=styled.div`
  display:none ;
  @media screen and (max-width: ${SCREENS.lg}){
    display:block ;
  }
`
const SearchBarDesktop=styled.div`
  display:block ;
  @media screen and (max-width: ${SCREENS.lg}){
    display:none ;
  }
`
const LoadMoreContainer= styled.div`
    
    width:100% ;
    grid-column: 1/-1 ;
    display:flex ;
    flex-direction:column ;
    align-items:center ;
`
const LoadMore =styled.span`
  display:inline-block ;
  text-align:center;
  width:8rem ;
  transition:all 0.5s ;
  background-color:#db2777 ;
  font-size: 24px;
  color:white;
  padding: 0.25rem 1rem;
  border-top-left-radius: 0.5rem;
  border-top-right-radius: 0.5rem;
  border-bottom-left-radius: 2rem;
  border-bottom-right-radius: 2rem;
  cursor: pointer;
  &:hover{
    transform: translateY(0.25rem);
  }
`
const LoadMoreIcon=styled(FontAwesomeIcon)`
  height:1.5rem ;
`

export default function Home({posts}) {
  const [loadNumber, setLoadNumber]=useState(8)
  return (
    <Container >
      <Head>
        <title>Aff Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBarMobile>
        <SearchBar />
      </SearchBarMobile>
      <FeaturedPosts />
      <BodyContainer>
        <PostsContainer>
          {posts.slice(0,loadNumber).map((post,index)=>{
            return (
              <PostCard key={post.node.title} post={post.node} />
            )
          })}
          {posts.length>loadNumber&&<LoadMoreContainer>
            <LoadMore onClick={()=>setLoadNumber(loadNumber+8)}>
              <LoadMoreIcon icon={faAnglesDown} />
            </LoadMore>
          </LoadMoreContainer>}
        </PostsContainer>
        <SideContainer>
          <SearchBarDesktop>
          <SearchBar />
          </SearchBarDesktop>
          <SideBarContainer>
            <PostWidget />
            <Categories />
          </SideBarContainer>
        </SideContainer>
      </BodyContainer>
    </Container>
  )
}

export async function getStaticProps(){
  const posts= await getPosts()||[];
  posts.reverse();
  return {
    props:{posts}
  }
}